oughtinc/mosaic

README.md, server/config/config.json, server/test/lib/models/workspace.spec.ts, server/test/testHelpers/graphQLCalls.ts, server/test/testHelpers/graphqlQueries.ts
Just a few fixes that I came across when trying to run the backend tests.
=> Fix backend tests

client/src/lib/slate-pointers/PointerImportNode.tsx
See https://github.com/oughtinc/mosaic/issues/140
I'm still getting a feel for the pointer system. Not 100% confident this is the best way to implement this feature. As I understand more of the big picture I might refactor.
=> Click read-only pointers directly to toggle expansion

server/lib/schema/index.ts
This is pretty much the simplest solution I can think of to the Auth0 rate-limiting issue.
=> Add simple auth caching

client/src/slate-helpers/slate-change-mutations/normalizeChange.js
Resolves #156. Ended up being very straightforward.
=> Resolve backspace bug

client/src/lib/slate-pointers/PointerImportNode.tsx, client/src/lib/slate-pointers/ShowExpandedPointer.tsx, client/src/pages/RootWorkspacePage/index.tsx
See #154. This also addresses the comment in that issue about the extra space.
=> Style imports to look like exports

client/src/components/BlockEditor/BlockEditorEditing.tsx
=> End import autocomplete on any non-numeric key

client/src/auth.tsx, server/lib/schema/index.ts
We might want to restrict this to just eligible workspaces after we have that infrastructure in place.
=> Allow all users to edit workspaces

server/package.json, server/yarn.lock
Type checking wasn't properly set up on the server, so it wasn't happening. I set things up so that type-checking now occurs. Unsurprisingly, this uncovered a lot of type errors. I'll plan to address them in a future PR.
=> Add server-side type-checking

client/src/components/BlockEditor/BlockEditorEditing.tsx, server/lib/models/index.js
Merge preview branch into temporary trial app
=> Preview branch v0.3

client/package.json, client/src/components/WorkspaceCard/WorkspaceCard.tsx, client/src/components/WorkspaceCard/index.tsx, client/src/pages/EpisodeShowPage/index.tsx, client/yarn.lock
This PR adds the following feature. When an oracle for a workspace clicks on the "Entire Tree" nav button, the tree that is opened will automatically scroll down to that workspace. Also, the workspace is now highlighted so there's a visual indication it's the active workspace.
=> Auto scroll in tree view

client/package.json, client/src/components/NewBlockForm.tsx, client/src/lib/slate-pointers/PointerImportNode.tsx, client/src/pages/EpisodeShowPage/ChildrenSidebar.tsx, client/src/pages/EpisodeShowPage/ResponseFooter.tsx, client/src/pages/EpisodeShowPage/index.tsx, client/yarn.lock, server/lib/models/helpers/defaultHonestOracleBlocks.ts, server/lib/models/helpers/defaultMaliciousOracleBlocks.ts, server/lib/models/helpers/defaultRootLevelBlocks.ts, server/lib/models/workspace.ts, server/lib/scheduler/Schedule.ts, server/lib/scheduler/Scheduler.ts, server/lib/scheduler/UserSchedule.ts, server/lib/schema/helpers/getMessageForUser.ts, server/lib/schema/index.ts
1. Root workspace is assigned to a malicious oracle, and now just involves the creation of the question. Honest oracle gets the root workspace's child.
2. Instructions appear outside of the scratchpad, and change depending on whether it is an oracle's first or second+ time assigned to the workspace.
3. Oracles have two buttons they can use to finish working on a workspace: one ("Next workspace") that takes them to their next assignment without reactivating their parent or submitting the answer, and one ("Done & bubble answer up") that reactivates the parent and submits the answer.
=> Malicious oracle rework

client/src/components/BlockEditor/BlockEditorEditing.tsx, client/src/pages/EpisodeShowPage/ResponseFooter.tsx, client/src/pages/EpisodeShowPage/index.tsx
=> Only enable done button when the response block has content

client/src/components/BlockEditor/BlockEditorEditing.tsx, client/src/components/WorkspaceCard/index.tsx, client/src/helpers/getActiveWorkspaceIsFromQueryParams.ts, client/src/helpers/getDoesWorkspaceHaveTimerFromQueryParams.ts, client/src/helpers/getExperimentIdOrSerialIdFromQueryParams.ts, client/src/helpers/getIsTreeExpandedFromQueryParams.ts, client/src/helpers/getIsUserInExperimentFromQueryParams.ts, client/src/helpers/getMomentDurationForWorkspaceTimerFromQueryParams.ts, client/src/lib/slate-pointers/PointerExportMark.tsx, client/src/pages/BetweenEpisodesPage.tsx, client/src/pages/CompactTreeView/CompactTreeGroup.tsx, client/src/pages/CompactTreeView/index.tsx, client/src/pages/EpisodeShowPage/WorkspaceRelations.ts, client/src/pages/EpisodeShowPage/index.tsx, client/src/pages/NextEpisodeShowPage.tsx, client/src/pages/NextMaybeSuboptimalEpisodeShowPage.tsx, client/src/pages/WorkspaceSubtreePage/index.tsx, server/lib/models/experiment.ts, server/lib/schema/index.ts
Just a refactor; no user-facing changes.
1. `findByPkOrSerialId` added to Experiment model instead of freestanding function in schema.
2. Frontend query param logic factored out into one place. It's no longer in React components.
=> Refactor shorter urls

client/src/pages/CompactTreeView/CompactTreeGroup.tsx, client/src/pages/CompactTreeView/LazyUnlockGroup.tsx, client/src/pages/CompactTreeView/NormalWorkspaceGroup.tsx, client/src/pages/EpisodeShowPage/index.tsx
=> Show malicious compact tree

README.md
Adds documentation and will be the first run of autodeploy
closes #631
=> feat: autodeploy master on heroku

README.md, client/src/components/Header/index.tsx, client/src/components/WorkspaceCard/WorkspaceCard.tsx, client/src/components/helpers/convertActionTypeToReadableString.ts, client/src/pages/EpisodeShowPage/EpisodeNav.tsx
=> Rename Needs More Work button -> Skip Workspace

client/src/pages/EpisodeShowPage/index.tsx
=> [WIP] Show link to original document in Experts workspace

README.md
Thanks to Zak for this approach
=> Add README section on offline development

server/lib/schema/index.ts
closes #594
Adds await calls, even though it will slightly slow down the script, to guarantee consistent behavior.
=> Correct stale behavior on API-based experiment creation

README.md, client/public/index.html, client/src/App.tsx, client/src/index.tsx
closes #588. Reach out to Andrew Schreiber or Ben Rachbach for login information. Currently the system tracks chat users via Intercoms built in functionality, which allows chat users to enter their email. A future expansion could automatically include emails for logged in users. The Intercom widget should appear on all pages within Mosaic.
=> Intercom integration

client/src/components/BlockEditor/BlockEditorEditing.tsx, client/src/components/BlockEditor/MenuBar.tsx, client/src/components/BlockEditor/index.tsx, client/src/components/NewBlockForm.tsx, client/src/modules/blocks/charCounts.ts, client/src/pages/EpisodeShowPage/index.tsx
closes #647
Character count display is ready. Need to add logic to only show on editable fields.
=> Character Counter on Input Fields

client/src/pages/NextEpisodeShowPage.tsx
=> Remove find suboptimal workspace button

server/lib/models/user.ts, server/lib/schema/index.ts
closes #572
see https://github.com/oughtinc/mosaic-api-scripts/pull/16
=> Update Existing Trees (for API)

client/src/components/NewBlockForm.tsx, client/src/pages/EpisodeShowPage/ChildrenSidebar.tsx, client/src/pages/EpisodeShowPage/index.tsx, server/lib/models/workspace.ts
=> Hide archive button for non-root workspaces

client/src/components/WorkspaceHistory.tsx
=> Display snapshots in chronological order

client/src/pages/EpisodeShowPage/ChildrenSidebar.tsx
=> Remove 'Wait for Answer' for MIB

.vscode/launch.json, client/src/pages/NextEpisodeShowPage.tsx, server/lib/index.ts, server/lib/models/notificationRequest.ts, server/lib/models/workspace.ts, server/lib/notifiers/index.ts, server/lib/scheduler/Scheduler.ts, server/lib/scheduler/index.ts, server/lib/schema/index.ts, server/lib/utils/pickRandomItemFromArray.ts, server/test/lib/scheduler/Scheduler.spec.ts
Refactors scheduling logic to combine queries into bigger batches and remove redundant/outdated computation.
closes #743
=> Scheduling performance improvements

client/src/pages/NextEpisodeShowPage.tsx, server/lib/models/workspace.ts, server/lib/schema/index.ts
=> Fix request errors on workspace & findNextWorkspace
